### ISSUE TITLE
토이 프로젝트 - 이규리

### ISSUE THREAD

**Issue by cu29635** [interface-2021/Arduino_Study_Team#12]
아두이노 토이 프로젝트 - 이규리

** 주제 ** 
실내 미세먼지 농도 모니터링 및 먼지농도측정 센서를 이용한 공기청정기 작동 

** 기능 **
- 미세먼지 농도 수치가 어느 지점을 넘어서면 공기청정기가 자동으로 작동되게 한다. 
- 또는 이게 아니라도 직접 미세먼지 농도를 핸드폰으로 확인하고 무선으로 작동하게 한다
- 핸드폰 앱을 통해 실시간 미세먼지 모니터링 – 서버 사용해야함 (만약 어렵다면 블루투스로 근방확인 정도) 

** 필요 부품 **
1) 먼지측정센서 
 - PM2.5 GP2Y1023AU0F 먼지센서, 먼지측정센서, 먼지감지센서 - 10,890원
 - PM2008(좀더 가격대 있는 친구) - 25,000원
2) 와이파이통신이 가능한 아두이노 
 - 아두이노 ESP8266 와이파이 실드 [SZH-EK089] 13,200원 + 아두이노 우노 R3 호환보드 [SZH-EK002](아두이노 우노 R3) 12,980원
 - 아두이노 우노 IoT 보드 WeMos D1 R1 [SZH-EK080] 6,490원
 - 아두이노 우노 23,100원 + 와이파이 or 블루투스 모듈
3) [DFROBOT] 아두이노용 1602 LCD 키패드 실드 [DFR0009] 
(만약 앱을 만들어서 수치를 확인할 수 있다면 굳이 필요 없음.)
4) 아두이노 신호등 LED 모듈[ELB061002] - 2,640원
(이것도 굳이 없어도 상관없음. 미세먼지 농도에 따른 색 변화 – 현재 장소의 먼지 수치를 알 수 있음)
5) 미세먼지 센서 연결 쉴드 or 어뎁터
 - PM20008 연결 쉴드 - 6,600원
 - GP2Y10 먼지 센서 아답터 보드 [ELB050211] - 1,980원
6) 온습도 센서(만약 온도도 보여줄 수 있다면,,) 2,970원 – 위에 많이 복잡하면 굳이 추가하지 않는다.
7) 케이블 F/M
8) 테이프
9) 기존에 있는 공기청정기를 작동시킬 물리적인 힘 or 연결 도구
(모터?? 또는 사용)

**Comment by riyenas0925** [comment]
@cu29635 상세하게 잘 작성하셨습니다. 

이제 검색하신 것 중에 제작에 사용할 부품을 선정해야 하는데 제가 아래에 고민해야 할 것들을 적어뒀는데 한번 읽어보시고 고민해보세요.  👍 

1.먼지측정 센서 선정
* 프로젝트의 요구 성능에 따라 센서를선정해야 하는데 두 가지 센서의 측정 범위라던지 정밀도를 확인해보고 제작해보시면 될 것 같아요 -> 데이터 시트를 찾아보시면 좋을 것 같습니다. 아래처럼 상품 상세 설명 또는 관련 자료에 보시면 됩니다!

![image](https://user-images.githubusercontent.com/32615702/116958172-a834aa00-acd4-11eb-85ed-014ea8db884c.png)

2. 와이파이 모듈 선정
검색하신 모듈을 크게두 가지 방식으로나눌 수 있을 것같아요. 아래중에 선택하시면 될 것 같습니다.
* 아두이노 + 와이파이 모듈 (ArduinoUnoo +ESP82666)
* 와이파이 모듈 WeMoss D1 R1) -> 아두이노와 동일하게 스케치를 통해 코딩 가능

3. 기능세분화하기기
개발하기 전에 정의하신 기능을 세분화하는게 나중에 개발하기에 더 좋을 것 같아요. 예를 들면 ```미세먼지 농도 수치가 어느 지점을 넘어서면 공기청정기가 자동으로 작동되게 한다.``` 같은 경우는 ```미세먼지 농도 수치가 10ug/m3 이이 넘어가면 공기청정기를 50초간 작동시키고 알림을 울린다.``` 라는 식으로세분화하면면 나중에개발할 때 좋을 것 같습니다.
