### ISSUE TITLE
토이 프로젝트- 권태영

### ISSUE THREAD

**Issue by KwonTaeyoung247** [interface-2021/Arduino_Study_Team#13]
```
주제: 소리 센서와 블루투스 센서를 통한 구역 환경 소음 측정

기능

- 소리 센서를 통해 그 장소의 소음 데시벨 측정 

- 데시벨 값을 lcd 디스플레이에 표시 (3초 마다 다른 소음센서 데시벨 값으로 변경)

- 버튼을 누르면 lcd에  그 버튼에 해당하는 소음 센서 데이터 값 표시

-모든 소음 센서 데이터 값은 블루투스를 통해 다른 전자 기기로 전달


필요한 부품

-아두이노 우노 보드

-음압레벨 사운드 센서 모듈 

-3.3V 백라이트 16x2 LCD1602 모듈

-버튼 모듈

-HM-10 블루투스 4.0 BLE 모듈






```

**Comment by riyenas0925** [comment]
@KwonTaeyoung247 잘 정리하셨습니다!

이제 검색하신 것 중에 제작에 사용할 부품을 선정해야 하는데 제가 아래에 고민해야 할 것들을 적어뒀는데 한번 읽어보시고 고민해보세요. 👍

1. 소리 측정 센서 선정
음압레벨 센서라고 하셨는데 이센서가 출력이 디지털로 db값을 출력해주는건지 아니면 단순히 아날로그 전압으로 출력해서 사용자가 공식을 이용해서 db로 바꿔줘야 하는지 찾아보셔야 할 것 같습니다 ->  데이터 시트를 찾아보시면 좋을 것 같습니다. 아래처럼 상품 상세 설명 또는 관련 자료에 보시면 됩니다!

![116958172-a834aa00-acd4-11eb-85ed-014ea8db884c](https://user-images.githubusercontent.com/32615702/117451724-d7ba0f80-af7d-11eb-8e98-8ae61a5dcabc.png)

2. LCD 모듈 선정
문자를 출력하기 위한 LCD 모듈을 CLCD라고 하는데 CLCD도 16핀 전부 연결해서 제어하는 방식이 있고 I2C나 시리얼로 적은 핀을 사용해 제어하는 방식도 있습니다 한번 검색해보시고 아두이노 우노에서 사용해야 할 핀이 많아 LCD에 많은 핀을 할당하지 못할 것 같다면 고려해보는 것도 좋을 것 같아요

3. 기능세분화하기기
개발하기 전에 정의하신 기능을 세분화하는게 나중에 개발하기에 더 좋을 것 같아요. 예를 들면 ```미세먼지 농도 수치가 어느 지점을 넘어서면 공기청정기가 자동으로 작동되게 한다``` 같은 경우는 ```미세먼지 농도 수치가 10ug/m3 이이 넘어가면 공기청정기를 50초간 작동시키고 알림을 울린다.``` 라는 식으로세분화하면면 나중에개발할 때 좋을 것 같습니다.
