### ISSUE TITLE
토이 프로젝트- 박민재

### ISSUE THREAD

**Issue by reo12356** [interface-2021/Arduino_Study_Team#14]
주제
 인체감지 센서를 이용해 움직임을 감지해 전등을 키거나 원격으로 제어한다

기능

- 인체감지 센서를 이용해 움직임을 감지하고 일시적으로 불을 킨다

- 움직임이 감지될시 휴대폰으로 알림이 오게한다

-휴대폰으로도 전등을 제어

필요한 부품

-아두이노 우노 보드
-wifi iot 모듈(5000~8000원)
-led(100원)
-아두이노 인체감지 센서모듈 PIR Motion Sensor Module(3100원)
-아두이노 1채널 5V 미니 릴레이 모듈(960원)

**Comment by riyenas0925** [comment]
@reo12356 잘 작성하셨습니다.

1. 인체감지 센서 선정
인체감지 센서도 종류가 여러가지(대표적으로는 PIR센서)가 있는데 어떤 부품을 사용하실 예정인가요?
그리고 센서를 선정할 때는 센서의 측정 범위라던지 정밀도를 확인해보고 제작하는 게 좋습니다. 아래처럼 상품 상세 설명 또는 관련 자료를 확인해보시는 걸 추천해 드려요

![116958172-a834aa00-acd4-11eb-85ed-014ea8db884c](https://user-images.githubusercontent.com/32615702/117246181-1e711200-ae77-11eb-957f-f9ee7bb78873.png)

2. 불?
여기서 불을 켠다고 적혀있는데 여기서 말하는 불이 220v의 형광등인지 아니면 조그마한 6\~12v 짜리 전구인지 아니면 LED인지 확실하게 정하는 게 설계하는 데 도움이 될 것 같네요
만약에 하신다면 **정확한 지식 없이 220v를 다루는 건 위험**할 것 같아서 실제 형광등하고 비슷하게 생긴 5\~12v 사이의 전구를 하나 구해서 사용하는 게 좋을 것 같아요!!!!
> 찾아보니 아래처럼 캠핑용 5v 전구로 검색하면 여러 개가 나오네요
>
![shop1 daumcdn](https://user-images.githubusercontent.com/32615702/117246554-d2729d00-ae77-11eb-838c-c067001c5440.jpg)

3. 기능 세분화하기
개발하기 전에 정의하신 기능을 세분화하는 게 나중에 개발하기에 더 좋을 것 같아요. 예를 들면 ```미세먼지 농도 수치가 어느 지점을 넘어서면 공기청정기가 자동으로 작동되게 한다.``` 같은 경우는 ```미세먼지 농도 수치가 10ug/m3 이이 넘어가면 공기청정기를 50초간 작동시키고 알림을 울린다.``` 라는 식으로 세분화하면 나중에 개발할 때 좋을 것 같습니다.
