### ISSUE TITLE
토이 프로젝트 - 부품 리스트(김준오)

### ISSUE THREAD

**Issue by JayUno** [interface-2021/Arduino_Study_Team#15]
주제: 초음파 센서와 모터를 이용해 미니 레이더 만들기

기능

- 초음파 센서를 통해 주변의 물건을 확인

- 모터에 초음파 센서를 달아서 회전시키면서 주변 감지

- 1m내에 물건이 감지될 경우 led가 들어오도록 설정

- 아두이노 컴파일러 내에서 레이더 망이 나오도록 설정

필요한 부품

-아두이노 우노 보드

-초음파 센서 

-모터

-led

![구조도](https://user-images.githubusercontent.com/83629800/117770611-172f7700-b270-11eb-9e50-ff9c37904b7c.jpg)

**Comment by riyenas0925** [comment]
@KIM-JUNO 전체적으로 잘 작성하셨습니다 👍 
* 초음파 센서 선정
초음파 센서도 종류가 여러가지(대표적으로는 SRF-04)가 있는데 어떤 부품을 사용하실 예정인가요?
그리고 센서를 선정할 때는 센서의 측정 범위라던지 정밀도를 확인해보고 제작하는 게 좋습니다. 아래처럼 상품 상세 설명 또는 관련 자료를 확인해보시는 걸 추천해 드려요

![116958172-a834aa00-acd4-11eb-85ed-014ea8db884c](https://user-images.githubusercontent.com/32615702/117451724-d7ba0f80-af7d-11eb-8e98-8ae61a5dcabc.png)


추가로 저는 이 토이 프로젝트 기획서를 읽고 추후에 프로세싱으로 실제 레이더처럼 보여준다면 좋을 것 같다는 생각이 들었어요

* https://opentutorials.org/course/1873/12254

**Comment by riyenas0925** [comment]
https://www.youtube.com/watch?v=r7dEU8PaVgU
