### ISSUE TITLE
토이 프로젝트 - 부품리스트(박민재)

### ISSUE THREAD

**Issue by reo12356** [interface-2021/Arduino_Study_Team#16]
주제 인체감지 센서를 이용해 움직임을 감지해 전등을 키거나 원격으로 제어한다

기능
* 모션센서에 움직임이 감지되는 동안 전구를 켠 후 움직임이 없어지면 5초후 불이 꺼진다.

*  모션센서에 움직임이 감지되면 앱을 통해 푸시 알림이 온다

* 앱을 통해서 전구 제어가 가능하며 앱으로 전구를 켜고있는 동안은 푸시알림이 중지된다 

필요한 부품

-아두이노 우노 IoT 보드 WeMos D1 R1 [SZH-EK080](5900원) 
-[Coms] USB 램프(전구형), Blue/5V 5W, 캠핑용 1M[ND741](2,300원)
- 아두이노 적외선 PIR 인체감지센서 모듈 V2(4800원) 
-아두이노 1채널 5V 미니 릴레이 모듈(960원)

<img width="391" alt="스크린샷 2021-05-10 오전 1 37 01" src="https://user-images.githubusercontent.com/81216734/117580038-db41c800-b130-11eb-806b-b7e08e699cca.png">

[20210510_장바구니목록.xls](https://github.com/interface-2021/Arduino_Study_Team/files/6448013/20210510_.xls)

**Comment by riyenas0925** [comment]
@reo12356 

- 모션센서에 움직임이 감지되면 앱을 통해 푸시 알림이 온다
    →  푸시 알림은  FCM(Firebase Cloud Messaging), GCM(Google Cloud Messaging) 서비스를 한번 찾아보세요
    → 푸시 알림을 사용하지 않는다면 이것도 계속 서버의 값을 체크하면서 값이 변경된다면 특정 동작을 하면 됩니다.

- 앱을 통해서 전구 제어가 가능하며 앱으로 전구를 켜고있는 동안은 푸시알림이 중지된다
    → 제일 정석적인 방법은 웹 소켓 방식을 사용하는 방법입니다.
    → 간단하게 구현하는 방법은 아두이노에서 일정 주기로 서버의 값을 읽어서 값이 변경된다면 LED의 상태를 변경해주면 되겠네요

**Comment by riyenas0925** [comment]
서버 (프레임워크)
python : django, flask
javascript : node.js
java : spring, spring boot
