### ISSUE TITLE
토이 프로젝트 - 부품리스트 (이규리)

### ISSUE THREAD

**Issue by cu29635** [interface-2021/Arduino_Study_Team#17]
**주제**
실내 미세먼지 농도 모니터링 
(원래는 공기청정기 제어까지 하려 했으나 기술적으로 직접 공기청정기를 제작하는 것이 아니면 구현하기 힘든 듯해서 모니터링만 하기로 결정)

**부품리스트**
[아두이노_토이 프로젝트 부품리스트 _이규리.xls](https://github.com/interface-2021/Arduino_Study_Team/files/6449141/_._.xls)
먼지센서 어답터는 필요치 않아보여서 포함 안시킴. 혹시 필요하다 생각들면 추가 구매

**토이프로젝트 구조도**
<img width="1440" alt="스크린샷 2021-05-10 오전 11 43 49" src="https://user-images.githubusercontent.com/77824364/117600706-6ea5e800-b187-11eb-8226-8cd0b7f4aa52.png">

**세부기능**
미세먼지 센서 측정 수치가 30㎍/m³를 초과하면 노란불 전환(보통), 80㎍/m³를 초과하면 빨간불로 전환(위험)

**Comment by riyenas0925** [comment]
@cu29635 

- 공기청정기가 아니더라도 미세먼지 수치가 높아지면 특정 행동을 한다는 걸 보여주도록 LED나 모터를 추가로 달아 보여주는 것도 좋을 것 같아요
- wifi를 이용해서 ThingSpeak에서 정해진 통신 프로토콜에 맞춰 전송하면 됩니다.
- 신호등 모듈을 사용하셔도 좋고 아래처럼 멀티컬러 LED를 사용하셔도 좋습니다.

 [https://www.devicemart.co.kr/goods/catalog?code=000600020006](https://www.devicemart.co.kr/goods/catalog?code=000600020006)

**Comment by riyenas0925** [comment]
https://kr.mathworks.com/help/thingspeak/writedata.html
https://www.devicemart.co.kr/goods/view?no=1192634
