### ISSUE TITLE
토이 프로젝트- 부품 리스트 (권태영)

### ISSUE THREAD

**Issue by KwonTaeyoung247** [interface-2021/Arduino_Study_Team#18]
```
주제: 소리 센서와 블루투스 센서를 통한 구역 환경 소음 측정

기능

- 소리 센서를 통해  장소의 소음 아날로그 데이터  측정 

- 공식을 통해 데이터 값을 dB 값으로 변환


- 버튼을 누르면 디스플레이에  그 버튼에 해당하는  데이터 값 표시
  ㄴ 만약 데이터 값이 60dB 이상이면 메인보드에서 불빛이 1초 간격으로 점멸 및 디스플레이 두번째 칸에 경고 
       문구 출력

-블루투스 센서를 통해 핸드폰 연동을 하고  어플 제작(어플은 디스플레이와 버튼들로 구성 작동 방식 동일)

필요한 부품

-아두이노 우노 보드

-사운드 센서 모듈 [SZH-EK087]

-3.3V 백라이트 16x2 LCD1602 모듈 (4핀 연결_납땜 x)

-버튼 모듈

-HM-10 블루투스 4.0 BLE 모듈


```
![1111](https://user-images.githubusercontent.com/59225295/117710306-eec26100-b20c-11eb-9a38-80fc83048789.png)

[제품 문서.xlsx](https://github.com/interface-2021/Arduino_Study_Team/files/6454379/default.xlsx)

**Comment by riyenas0925** [comment]
@KwonTaeyoung247 

* 찾으신 제품을 확인해보니 I2C방식의 LCD입니다 I2C 제어 함수 또는 I2C LCD를 제어할 수 있는 라이브러리를 찾아보시면 좋을것 같습니다. 
* 메인보드의 불빛은 디지털핀 13번에 연결되어있는 LED가 맞나요? 여기서 각각의 소리센서에 대한 LED를 켜려면 외부에 LED를 추가적으로 달면 좋겠네요
