### ISSUE TITLE
1주차 미션 - 박서연

### ISSUE THREAD

**Issue by SeoYeon-02** [interface-2021/Arduino_Study_Team#2]
```
void setup()
{
  pinMode(13, OUTPUT);
  pinMode(12, OUTPUT);
}

void loop()
{
  digitalWrite(13, HIGH);
  delay(500);
  digitalWrite(13, LOW);
  delay(500); 
  
  digitalWrite(12, LOW);
  delay(500); 
  digitalWrite(12, HIGH);
  delay(500); 
}
```
<img width="688" alt="캡처" src="https://user-images.githubusercontent.com/81216824/112719509-a68cff00-8f3c-11eb-8b5f-e25ac3cd82e4.PNG">

**Comment by riyenas0925** [comment]
@SeoYeon-02 
아두이노 void loop문 안에서는 절차적으로 동작합니다! 따라서 위에 코드를 타이밍 차트로 그려보면 아래처럼 동작합니다.
![Notes_210401_120456_1](https://user-images.githubusercontent.com/32615702/113237983-da707780-92e2-11eb-85ff-74833a24a129.jpg)
이번 미션에서 제시한 동작을 하려면 아래처럼 코드를 작성해야 합니다. 한 번 타이밍 차트를 그려보면서 코드를 이해해보시면 좋을 것 같아요 👍 

```
void loop()
{
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(500); 
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW); 
  delay(500);
}
```
